### ISSUE TITLE
Need to invoke refresh before using application default credentials.

### ISSUE THREAD

**Issue by farmdawgnation** [GoogleCloudPlatform/build-artifacts-maven-tools#12]
Builds locally are working great. When I attempt to invoke a gradle build in CI with your plugin enabled, I'm getting a null pointer exception on [this line](https://github.com/GoogleCloudPlatform/build-artifacts-maven-tools/blob/0e6cc14e4191c9ba2e6c06fdb0db5e54905f680a/buildartifacts-gradle-plugin/src/main/java/com/google/cloud/buildartifacts/gradle/plugin/BuildArtifactsGradlePlugin.java#L102).

It looks like after default application credentials are retrieved [around here](https://github.com/GoogleCloudPlatform/build-artifacts-maven-tools/blob/94b60406bddac032e9958ccc01864a8665423946/buildartifacts-auth-common/src/main/java/com/google/cloud/buildartifacts/auth/DefaultCredentialProvider.java#L34) the `refresh` method needs to be invoked otherwise the access token will be `null` and trigger the NPE I'm seeing.

**Comment by kevinmdavis** [comment]
We've made a 1.1.2 release which should fix this issue. However, it may take a few hours for the release to show up in Maven Central and the Gradle plugin repository.

Let me know if you run into any other problems.
