### ISSUE TITLE
May need to be reimplemented as a Plugin<Gradle> to support settings files

### ISSUE THREAD

**Issue by farmdawgnation** [GoogleCloudPlatform/build-artifacts-maven-tools#15]
I'm using the build artifacts repository to host a gradle plugin (among other things) that configures all of my default settings in the build. To do this, I've set up my build artifacts repo as a custom plugin repository. So my `settings.gradle` looks like:

```
pluginManagement {
  plugins {
    id "com.google.cloud.buildartifacts.gradle-plugin" version "1.1.2"
  }
  repositories {
    maven {
      url "buildartifacts://maven.pkg.dev/[redacted]/[redacted]"
    }
    gradlePluginPortal()
  }
}
```

However, this fails with the following error in cloud build:

```
* What went wrong:
Error resolving plugin [id: '[redacted]', version: '[redacted]']
> Could not resolve all dependencies for configuration 'detachedConfiguration1'.
> Not a supported repository protocol 'buildartifacts': valid protocols are [http, https, file, gcs, s3, sftp]
```

Doing a bit of digging it looks as though the plugin isn't getting applied to the settings object that's generated from `settings.gradle`. I _think_ (but am not sure) that reimplementing the plugin as a `Plugin<Gradle>` would cause it to process the [Gradle object](https://docs.gradle.org/current/javadoc/org/gradle/api/invocation/Gradle.html) and permit you to use the `settingsEvaluated` helper to process the URLs that appear in the `settings.gradle` file.

You would then need to update how you reference the `afterEvaluate` hook on the project to operate on `gradle.getRootProject()` since a `Gradle` instance would get injected instead of a `Project` instance.

**Comment by molian6** [comment]
Thanks Matt for your feedback. We'll take a look at this shortly.

**Comment by molian6** [comment]
Hello Matt, sorry for the delayed updates. Sending out a PR to fix that issue: https://github.com/GoogleCloudPlatform/build-artifacts-maven-tools/pull/18

Will keep you updated on the new releases.

**Comment by farmdawgnation** [comment]
Thank you!

**Comment by molian6** [comment]
#19 New version of gradle published to gradle plugin portal with setting.gradle support.
