### ISSUE TITLE
Gradle: Not a supported repository protocol 'artifactregistry' in settings.gradle

### ISSUE THREAD

**Issue by kikoso** [GoogleCloudPlatform/build-artifacts-maven-tools#90]
Hi folks,

There was a very similar issue reported in https://github.com/GoogleCloudPlatform/artifact-registry-maven-tools/issues/40. Apparently, adding the repository to `settings.gradle` still raises this error.

Would it be possible to extend a fix to support also the repository URL in `settings.gradle`? This can be useful in certain projects, specifically Android ones can make extensive usage of this file.

**How to reproduce it:**

Move the repository URL to this block in the `settings.gradle` file:

```
dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
    repositories {
         maven {
            url "artifactregistry://us-west2-maven.pkg.dev/gmp-artifacts/maps"
        }
    }
}
```

**Comment by PPrydorozhnyi** [comment]
hey @kikoso, I think the same issue was raised in ticket #71
